version: '3'
services:
  db:
    image: mysql:5.7.24
    command: mysqld --character-set-server=utf8 --collation-server=utf8_bin
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_DATABASE: testdb
    volumes:
      - ./local/init:/docker-entrypoint-initdb.d
